<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE car_catalog [
<!ELEMENT planes_for_sale (ad+)>
<!ELEMENT ad (year, make, model, color, description,
price?, seller, location)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT make (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT seller (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ATTLIST seller phone CDATA #REQUIRED>
<!ATTLIST seller email CDATA #IMPLIED>
<!ENTITY c "Cessna">
<!ENTITY p "Piper">
<!ENTITY b "Beechcraft">
]>
<?xml-stylesheet type="text/css" href="2nd.css"?>
<planes_for_sale>
	<ad>
		<make> &c; </make>
		<year> 2001 </year>
		<model> BOND-007 </model>
		<color> Red and White </color>
		<description>We provide high quality services at our flights. </description>
		<price> Rs. 35,000 </price>
		<seller phone = "0852-8955214" email = "bond@bond.com"> Subway Aircraft </seller>
		<location>
			<city> Bangalore </city>
			<state> Karnataka </state>
		</location>
	</ad>
	<ad>
		<make> &p; </make>
		<year> 2004 </year>
		<model> Boeing 777 </model>
		<color> White and Black </color>
		<description> We have the largest seating capacity compare to any. </description>
		<price> Rs. 25,000 </price>
		<seller phone = "04564-5547122" email = "amin@boeing.com"> Prajwal John's  Aircraft </seller>
		<location>
			<city>Chennai </city>
			<state> Tamilunadus </state>
		</location>
	</ad>
	<ad>
		<make> &b; </make>
		<year> 2006 </year>
		<model> Jetways </model>
		<color>White and Blue</color>
		<description> We provide lowcost seats. </description>
		<price> Rs. 17,000 </price>
		<seller phone = "022-2366515"> Legend's  Aircraft </seller>
		<location>
			<city> Mumbai </city>
			<state> Maharashtra </state>
		</location>
	</ad>
</planes_for_sale>